### ISSUE TITLE
Mailing list works?

### ISSUE THREAD

**Issue by mitar** [opendata-si/opendata.si#11]
I cannot open: http://lists.kiberpipa.org/mailman/listinfo/podatki

If that mailing lists are not working anymore, I can make it on my server, I already have an open access list: https://common.tnode.com/sympa/info/openaccess-list

cc @domenkozar, @zejn, @avian2, @gandalfar

**Comment by zejn** [comment]
No, mailing list is down, because it was hosted on now defunct server. You are welcome to host community mailing list, I will happily add it to the website.

**Comment by mitar** [comment]
OK. Do we have a roster of the previous list?

**Comment by zejn** [comment]
No, not really.

**Comment by mitar** [comment]
I made it here, feel free to subscribe to it. Also announce it around if possible.

**Comment by mitar** [comment]
Oh, a link: https://common.tnode.com/sympa/info/opendata-list

**Comment by domenkozar** [comment]
@zejn could you deploy new version now that https://github.com/opendata-si/opendata.si/pull/12 is merged?

**Comment by zejn** [comment]
Deployed.
